# .----------------.  .----------------.  .-----------------. .----------------.  .----------------.  .----------------.
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |     ______   | || |     ____     | || | ____  _____  | || |  _________   | || |     _____    | || |    ______    | |
#| |   .' ___  |  | || |   .'    `.   | || ||_   \|_   _| | || | |_   ___  |  | || |    |_   _|   | || |  .' ___  |   | |
#| |  / .'   \_|  | || |  /  .--.  \  | || |  |   \ | |   | || |   | |_  \_|  | || |      | |     | || | / .'   \_|   | |
#| |  | |         | || |  | |    | |  | || |  | |\ \| |   | || |   |  _|      | || |      | |     | || | | |    ____  | |
#| |  \ `.___.'\  | || |  \  `--'  /  | || | _| |_\   |_  | || |  _| |_       | || |     _| |_    | || | \ `.___]  _| | |
#| |   `._____.'  | || |   `.____.'   | || ||_____|\____| | || | |_____|      | || |    |_____|   | || |  `._____.'   | |
#| |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'

#how many jobs can a player have by default?
MaxDefaultJobs: 1

#do you want to use the levels?
Enable_Levels: true

#Date-Format
Date: "dd/MM/yyyy"

#format of example money, 10.05
Format: "0.00"

# Use "CLOSE", or "REOPEN"
Jobs_UpdateMode: "REOPEN"

#config of the main gui
Main_Name: "&b&lJobs Menu"

#options to the job items
Jobs:

  Lore:

    Bought:
      - "&7"
      - "&aYou own this Job."

    In:
      - "&7"
      - "&bYou are in this Job."

    Price:
      - "&7"
      - "&cClick to buy this job for <price> Dollars."

# -> 3 * 9
Main_Size: 5

Main_Custom:

  List:
    - "Close"
    - "Leave"
    - "Info"

  Close:

    Display: "&cClose Menu"

    Action: "CLOSE"

    Material: "RED_DYE"

    Slot: 41

  Leave:

    Display: "&4Leave all Jobs"

    Action: "LEAVE"

    Lore:
      - "&7Click here to leave all jobs"

    Material: "BARRIER"

    Slot: 40

  Info:

    Display: "&bInformations"

    Action: "NOTHING"

    Lore:
      - "&8&m-------------------"
      - "&cWhy i should get an job?"
      - "&7"
      - "&7You need an Job to earn money, "
      - "&7to raise your Kids! :)"

    Material: "BEACON"

    Slot: 39

Main_Place:
  - "BLACK_STAINED_GLASS_PANE:0:&7"
  - "BLACK_STAINED_GLASS_PANE:1:&7"
  - "BLACK_STAINED_GLASS_PANE:2:&7"
  - "BLACK_STAINED_GLASS_PANE:3:&7"
  - "BLACK_STAINED_GLASS_PANE:4:&7"
  - "BLACK_STAINED_GLASS_PANE:5:&7"
  - "BLACK_STAINED_GLASS_PANE:6:&7"
  - "BLACK_STAINED_GLASS_PANE:7:&7"
  - "BLACK_STAINED_GLASS_PANE:8:&7"
  - "BLACK_STAINED_GLASS_PANE:9:&7"
  - "BLACK_STAINED_GLASS_PANE:10:&7"
  - "BLACK_STAINED_GLASS_PANE:11:&7"
  - "RED_STAINED_GLASS_PANE:10:&7"
  - "RED_STAINED_GLASS_PANE:11:&7"
  - "RED_STAINED_GLASS_PANE:12:&7"
  - "RED_STAINED_GLASS_PANE:13:&7"
  - "RED_STAINED_GLASS_PANE:14:&7"
  - "RED_STAINED_GLASS_PANE:15:&7"
  - "RED_STAINED_GLASS_PANE:16:&7"
  - "BLACK_STAINED_GLASS_PANE:17:&7"
  - "BLACK_STAINED_GLASS_PANE:18:&7"
  - "RED_STAINED_GLASS_PANE:19:&7"
  - "RED_STAINED_GLASS_PANE:20:&7"
  - "RED_STAINED_GLASS_PANE:21:&7"
  - "RED_STAINED_GLASS_PANE:22:&7"
  - "RED_STAINED_GLASS_PANE:23:&7"
  - "RED_STAINED_GLASS_PANE:24:&7"
  - "RED_STAINED_GLASS_PANE:25:&7"
  - "BLACK_STAINED_GLASS_PANE:26:&7"
  - "BLACK_STAINED_GLASS_PANE:27:&7"
  - "BLACK_STAINED_GLASS_PANE:28:&7"
  - "BLACK_STAINED_GLASS_PANE:29:&7"
  - "BLACK_STAINED_GLASS_PANE:30:&7"
  - "BLACK_STAINED_GLASS_PANE:31:&7"
  - "BLACK_STAINED_GLASS_PANE:32:&7"
  - "BLACK_STAINED_GLASS_PANE:33:&7"
  - "BLACK_STAINED_GLASS_PANE:34:&7"
  - "BLACK_STAINED_GLASS_PANE:35:&7"
  - "BLACK_STAINED_GLASS_PANE:36:&7"
  - "BLACK_STAINED_GLASS_PANE:37:&7"
  - "BLACK_STAINED_GLASS_PANE:38:&7"
  - "BLACK_STAINED_GLASS_PANE:39:&7"
  - "BLACK_STAINED_GLASS_PANE:40:&7"
  - "BLACK_STAINED_GLASS_PANE:41:&7"
  - "BLACK_STAINED_GLASS_PANE:42:&7"
  - "BLACK_STAINED_GLASS_PANE:43:&7"
  - "BLACK_STAINED_GLASS_PANE:44:&7"

Command:
 
  #do not remove something here, if you dont want to use it, put "false" on Enabled!
  HELP:

    Enabled: true

    Usage: "help"
    
  LEAVE:

    Enabled: true

    Usage: "leave"
    
  LEAVEALL:

    Enabled: true

    Usage: "leaveall"
 
  STATS:

    Enabled: true

    Usage: "stats"
 
    Addon: "STATS_GUI"
    
  SALARY:

    Enabled: true

    Usage: "salary"
 
    Addon: "REWARDS_GUI"
 
 
#options menu
Settings_Name: "&bJob Options &8- <job>"

Settings_Size: 3

Settings_Custom:

  List:
    - "Close"
    - "Back"
    - "Earnings"
    - "Leave"
    - "MoneyList"

  Close:

    Display: "&cClose Menu"

    Action: "CLOSE"

    Material: "RED_DYE"

    Slot: 16

  Leave:

    Display: "&c&lLeave this Job"

    Action: "LEAVE"

    Material: "REDSTONE"

    Slot: 15

  Earnings:

    Display: "&6My Earnings this Month"

    Action: "EARNINGS"

    Lore:
      - "&7This works only when the addon is installed."

    Material: "EMERALD"

    Slot: 10

  MoneyList:

    Display: "&4See Earnings for different Blocks"

    Action: "MONEYLIST"

    Lore:
      - "&7This works only when the addon is installed."

    Material: "BOOK"

    Slot: 11

  Back:

    Display: "&4Go Back"

    Action: "BACK"

    Lore:
      - "&7Click here to get back to the main menu"

    Material: "BARRIER"

    Slot: 13

Settings_Place:
  - "BLACK_STAINED_GLASS_PANE:0:&7"
  - "BLACK_STAINED_GLASS_PANE:1:&7"
  - "BLACK_STAINED_GLASS_PANE:2:&7"
  - "BLACK_STAINED_GLASS_PANE:3:&7"
  - "BLACK_STAINED_GLASS_PANE:4:&7"
  - "BLACK_STAINED_GLASS_PANE:5:&7"
  - "BLACK_STAINED_GLASS_PANE:6:&7"
  - "BLACK_STAINED_GLASS_PANE:7:&7"
  - "BLACK_STAINED_GLASS_PANE:8:&7"
  - "BLACK_STAINED_GLASS_PANE:9:&7"
  - "BLACK_STAINED_GLASS_PANE:10:&7"
  - "BLACK_STAINED_GLASS_PANE:11:&7"
  - "BLACK_STAINED_GLASS_PANE:10:&7"
  - "BLACK_STAINED_GLASS_PANE:11:&7"
  - "BLACK_STAINED_GLASS_PANE:12:&7"
  - "BLACK_STAINED_GLASS_PANE:13:&7"
  - "BLACK_STAINED_GLASS_PANE:14:&7"
  - "BLACK_STAINED_GLASS_PANE:15:&7"
  - "BLACK_STAINED_GLASS_PANE:16:&7"
  - "BLACK_STAINED_GLASS_PANE:17:&7"
  - "BLACK_STAINED_GLASS_PANE:18:&7"
  - "BLACK_STAINED_GLASS_PANE:19:&7"
  - "BLACK_STAINED_GLASS_PANE:20:&7"
  - "BLACK_STAINED_GLASS_PANE:21:&7"
  - "BLACK_STAINED_GLASS_PANE:22:&7"
  - "BLACK_STAINED_GLASS_PANE:23:&7"
  - "BLACK_STAINED_GLASS_PANE:24:&7"
  - "BLACK_STAINED_GLASS_PANE:25:&7"
  - "BLACK_STAINED_GLASS_PANE:26:&7"