main: de.warsteiner.jobs.UltimateJobs
version: 0.1.6-SNAPSHOT
name: UltimateJobs
author: Warsteiner37
api-version: 1.18
softdepend: [WorldGuard, AlonsoLevels, WorldEdit]
depend: [UltimateAPI]

commands:
  jobs:
  jobsadmin: