main: de.warsteiner.jobs.UltimateJobs
version: 0.2.8
name: UltimateJobs
author: Warsteiner37
api-version: 1.13
softdepend: [WorldGuard, AlonsoLevels, WorldEdit, PlaceHolderAPI]
depend: [UltimateAPI]

commands:
  jobs:
  jobsadmin: