main: de.warsteiner.jobs.UltimateJobs
version: 0.2.5
name: UltimateJobs
author: Warsteiner37
api-version: 1.18
softdepend: [WorldGuard, AlonsoLevels, WorldEdit, PlaceHolderAPI]
depend: [UltimateAPI]

commands:
  jobs:
  jobsadmin: